Update symfony.yml

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -33,7 +33,7 @@ jobs:
         run: composer clear-cache
       - name: Install Dependencies
         run: |
-          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist || (echo "Composer install failed" && exit 1)
+          composer install || (echo "Composer install failed" && exit 1)
       - name: Create Database
         run: |
           mkdir -p data
